// Copyright (c) 2021 Mike "KemoNine" Crosson
// SPDX-License-Identifier: Apache-2.0
#pragma once

#ifdef ARDUX_HAND_LEFT
#ifdef ARDUX_SIZE_40P
#define F0P_LEADING_NONES
#define F0P_ROW_ONE_MID_NONES
#define F0P_BETWEEN_ROW_ONE_TWO_NONES
#define F0P_ROW_TWO_MID_NONES
#define F0P_BETWEEN_ROW_TWO_THREE_NONES
#define F0P_ROW_THREE_MID_NONES
#define F0P_BETWEEN_ROW_THREE_THUMBS_NONES
#define F0P_THUMB_MID_NONES
#define F0P_TRAILING_NONES
#endif
#define BIG_LEADING_NONES KC_NO,
#define BIG_BETWEEN_ROW_ONE_TWO_NONES      LCTL(KC_T),     KC_HOME, KC_UP,   KC_END,     KC_PGUP, KC_BSPC, KC_NO,
#define BIG_BETWEEN_ROW_TWO_THREE_NONES    LCTL(KC_SPACE), KC_LEFT, KC_DOWN, KC_RIGHT,   KC_PGDN, KC_ENT,  KC_NO,
#define BIG_BETWEEN_ROW_THREE_THUMBS_NONES KC_S,           KC_LBRC, KC_RBRC, KC_RBRC,    KC_NO,   LGUI(KC_E),
#define BIG_TRAILING_NONES , KC_SPACE, KC_ESC, KC_DELETE
#endif

#ifdef ARDUX_HAND_RIGHT
#ifdef ARDUX_SIZE_40P
#define F0P_LEADING_NONES
#define F0P_ROW_ONE_MID_NONES
#define F0P_BETWEEN_ROW_ONE_TWO_NONES
#define F0P_ROW_TWO_MID_NONES
#define F0P_BETWEEN_ROW_TWO_THREE_NONES
#define F0P_ROW_THREE_MID_NONES
#define F0P_BETWEEN_ROW_THREE_THUMBS_NONES
#define F0P_THUMB_MID_NONES
#define F0P_TRAILING_NONES
#endif
#define BIG_LEADING_NONES KC_BSPC, KC_PGUP, KC_HOME, KC_UP, KC_END, LCTL(KC_T),
#define BIG_BETWEEN_ROW_ONE_TWO_NONES KC_NO, KC_ENT, KC_PGDN, KC_LEFT, KC_DOWN, KC_RIGHT, LCTL(KC_SPACE),
#define BIG_BETWEEN_ROW_TWO_THREE_NONES KC_NO, LGUI(KC_E), KC_NO, KC_LBRC, KC_RBRC, KC_RBRC, KC_S,
#define BIG_BETWEEN_ROW_THREE_THUMBS_NONES KC_NO, KC_DELETE, KC_ESC, KC_SPACE,
#define BIG_TRAILING_NONES
#endif
